language: java

sudo: false

jdk:
  - openjdk8
  - openjdk11
  - openjdk13

install: true

script:
  - mvn clean install -Dgpg.skip=true

after_success:
  - mvn clean test javadoc:javadoc -Ddoclint=all


